services:
  keycloak-server:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}
    container_name: keycloak-server
    hostname: keycloak-server
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Djboss.http.port=8080
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres-server:5432/keycloak
      - KC_DB_SCHEMA=public
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=root
    command: [ "start-dev", "--import-realm" ]
    volumes:
      - ./keycloak/realm:/opt/keycloak/data/import
      - ./keycloak/theme:/opt/keycloak/themes
    depends_on:
      - postgres-server
    networks:
      - application-network

  postgres-server:
    image: postgres:${POSTGRES_VERSION}
    container_name: postgres-server
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - application-network

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_VERSION}
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres-server
    networks:
      - application-network